[CmdletBinding()]
param(
  [string]$ProjectId = "matjark-7ebc7",
  [string]$Region = "us-central1",
  [string[]]$FunctionNames = @("ensureDefaultAdminDaily"),
  [switch]$DryRun,
  [switch]$KeepArtifacts
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$functionsRoot = $PSScriptRoot
$indexPath = Join-Path $functionsRoot "index.js"
$backupPath = Join-Path $functionsRoot "index.js.legacy-cleanup.bak"
$generatedRelativePath = "./src/legacyScheduledCleanup.generated.js"
$generatedPath = Join-Path $functionsRoot "src\legacyScheduledCleanup.generated.js"
$generatedExportLine = "export * from `"$generatedRelativePath`";"
$safeSchedule = "0 0 1 1 *"
$safeTimeZone = "Etc/UTC"

function Write-Step {
  param([string]$Message)
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Test-RequiredCommand {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required command not found in PATH: $Name"
  }
}

function Format-Command {
  param(
    [string]$FilePath,
    [string[]]$ArgumentList
  )

  $parts = @($FilePath)
  foreach ($argument in $ArgumentList) {
    if ($argument -match "\s") {
      $parts += "`"$argument`""
      continue
    }
    $parts += $argument
  }

  return ($parts -join " ")
}

function Invoke-External {
  param(
    [string]$FilePath,
    [string[]]$ArgumentList,
    [switch]$AlwaysRun
  )

  $display = Format-Command -FilePath $FilePath -ArgumentList $ArgumentList
  Write-Host $display -ForegroundColor DarkGray

  if ($DryRun -and -not $AlwaysRun) {
    return ""
  }

  $output = & $FilePath @ArgumentList 2>&1 | Out-String
  if ($LASTEXITCODE -ne 0) {
    throw "Command failed:`n$display`n$output"
  }

  if ($output.Trim()) {
    Write-Host $output.TrimEnd()
  }

  return $output
}

function Get-FunctionListOutput {
  return Invoke-External -FilePath "firebase" -ArgumentList @(
    "functions:list",
    "--project", $ProjectId
  ) -AlwaysRun
}

function Assert-LegacyScheduledFunction {
  param([string]$FunctionName)

  $listOutput = Get-FunctionListOutput
  $matchingLine = $listOutput |
    Select-String -Pattern $FunctionName |
    Select-Object -First 1

  if (-not $matchingLine) {
    throw "Function '$FunctionName' was not found in project '$ProjectId'."
  }

  $line = $matchingLine.Line
  if ($line -notmatch "\bv1\b" -or $line -notmatch "\bscheduled\b") {
    throw "Function '$FunctionName' was not found as a deployed v1 scheduled function in project '$ProjectId'."
  }
}

function New-GeneratedShimContent {
  param([string[]]$Names)

  $exports = foreach ($name in $Names) {
@"
export const $name = functionsV1
  .region("$Region")
  .runWith({
    memory: "256MB",
    timeoutSeconds: 60,
    maxInstances: 1,
  })
  .pubsub.schedule("$safeSchedule")
  .timeZone("$safeTimeZone")
  .onRun(async () => {
    logger.info("Temporary legacy cleanup shim invoked.", {
      functionName: "$name",
      projectId: "$ProjectId",
    });
    return null;
  });
"@
  }

@"
import * as logger from "firebase-functions/logger";
import * as functionsV1 from "firebase-functions/v1";

// Auto-generated by cleanup-legacy.ps1.
// This shim is intentionally low-frequency and no-op. Its only purpose is to
// recreate missing scheduler plumbing for orphaned gen1 scheduled functions so
// Firebase CLI can delete them cleanly.

$($exports -join "`r`n")
"@
}

function Restore-Index {
  if (Test-Path $backupPath) {
    Move-Item -Force $backupPath $indexPath
  }
}

function Remove-GeneratedArtifacts {
  if ($KeepArtifacts) {
    return
  }

  if (Test-Path $generatedPath) {
    Remove-Item -Force $generatedPath
  }
}

Test-RequiredCommand -Name "firebase"

if (-not (Test-Path $indexPath)) {
  throw "Could not find functions index file at $indexPath"
}

if (-not (Test-Path (Split-Path -Parent $generatedPath))) {
  New-Item -ItemType Directory -Path (Split-Path -Parent $generatedPath) | Out-Null
}

foreach ($name in $FunctionNames) {
  if ($name -notmatch "^[A-Za-z0-9_]+$") {
    throw "Invalid function export name: $name"
  }
}

$originalIndex = Get-Content $indexPath -Raw
if ($originalIndex -match [regex]::Escape($generatedRelativePath)) {
  throw "functions/index.js already references $generatedRelativePath. Clean that up before running this script."
}

Write-Step "Validating target functions"
foreach ($functionName in $FunctionNames) {
  Assert-LegacyScheduledFunction -FunctionName $functionName
  Write-Host "Validated legacy scheduled function: $functionName" -ForegroundColor Green
}

try {
  Write-Step "Creating temporary cleanup shim"
  Copy-Item $indexPath $backupPath -Force
  Set-Content -Path $generatedPath -Value (New-GeneratedShimContent -Names $FunctionNames) -Encoding UTF8
  Set-Content -Path $indexPath -Value (($originalIndex.TrimEnd() + "`r`n" + $generatedExportLine + "`r`n")) -Encoding UTF8

  foreach ($functionName in $FunctionNames) {
    Write-Step "Deploying cleanup shim for $functionName"
    Invoke-External -FilePath "firebase" -ArgumentList @(
      "deploy",
      "--only", "functions:$functionName",
      "--project", $ProjectId
    ) | Out-Null

    Write-Step "Deleting orphaned legacy function $functionName"
    Invoke-External -FilePath "firebase" -ArgumentList @(
      "functions:delete",
      $functionName,
      "--region", $Region,
      "--project", $ProjectId,
      "--force"
    ) | Out-Null
  }

  if (-not $DryRun) {
    Write-Step "Verifying cleanup"
    $finalList = Get-FunctionListOutput
    foreach ($functionName in $FunctionNames) {
      $residualLine = $finalList |
        Select-String -Pattern $functionName |
        Select-Object -First 1

      if ($residualLine) {
        throw "Function '$functionName' still appears in the deployed function list after cleanup."
      }
    }
    Write-Host "Legacy scheduled cleanup completed successfully." -ForegroundColor Green
  } else {
    Write-Host "Dry run completed. No deploy or delete commands were executed." -ForegroundColor Yellow
  }
}
finally {
  Write-Step "Restoring local files"
  Restore-Index
  Remove-GeneratedArtifacts
}
