# =====================================================================
# POWERSHELL COMMANDS FOR RUNNING THE FLUTTER PROJECT
# Copy and paste these commands directly in PowerShell
# =====================================================================

# Navigate to project directory
cd D:\matjark

# ============ STEP 1: Clean and Get Dependencies ============
flutter clean
flutter pub get
flutter pub upgrade

# ============ STEP 2: Verify Setup ============
flutter doctor -v

# ============ STEP 3: Run on Chrome Web ============
flutter run -d chrome

# ============ STEP 4: Run on Android Device ============
# First, connect your Android device or start an Android emulator
# Then run:
flutter run -d android

# ============ STEP 5: Setup Firebase (IMPORTANT) ============
# Install FlutterFire CLI first (run once):
dart pub global activate flutterfire_cli
$env:PATH += ";$env:LOCALAPPDATA\Pub\Cache\bin"

# Run Firebase configuration:
flutterfire configure

# This will:
# 1. Ask you to select your Firebase project
# 2. Generate lib/firebase_options.dart
# 3. Update android/ and ios/ directories automatically
# 4. Add necessary dependencies to pubspec.yaml

# ============ STEP 6: Build for Production ============

# Build Web:
flutter build web --release
# Output: build\web\

# Build Android APK:
flutter build apk --release
# Output: build\app\outputs\apk\release\app-release.apk

# Build Android App Bundle (for Play Store):
flutter build appbundle --release
# Output: build\app\outputs\bundle\release\app-release.aab

# ============ STEP 7: Check for Errors ============
flutter pub audit
flutter analyze

# ============ BACKUP COMMANDS ============

# If you encounter issues, backup and clean:
# Backup pubspec.lock:
Copy-Item pubspec.lock pubspec.lock.backup

# Clean everything:
flutter clean
Remove-Item .\build -Recurse -Force
Remove-Item .\windows -Recurse -Force -ErrorAction SilentlyContinue

# Reinstall:
flutter pub get

# ============ HELPFUL DEBUGGING COMMANDS ============

# View all errors with verbose output:
flutter run -d chrome -v

# Check Doctor output for specific issues:
flutter doctor -v

# View installed packages:
flutter pub deps

# Upgrade all packages to latest compatible versions:
flutter pub upgrade --major-versions

# ============ ABBREVIATIONS & TIME Savers ============

# Alias for quick run:
function dev { flutter run -d chrome }

# Alias for quick build web:
function bweb { flutter build web --release }

# Alias for quick analyze:
function check { flutter analyze }

# ============ IMPORTANT NOTES ============

# 1. FirebaseOptions.dart:
#    - Automatically generated by: flutterfire configure
#    - Contains credentials for different platforms (web, android, ios)
#    - Only needs to be generated once unless Firebase project changes

# 2. Phone Authentication on Web:
#    - Requires reCAPTCHA v3 setup in Firebase Console
#    - Automatically handled by Firebase SDK
#    - Test with real phone numbers (starting with +)

# 3. For macOS development:
#    - flutter_facebook_auth is intentionally removed from pubspec.yaml
#    - Web builds don't require it
#    - If you need Facebook auth, uncomment the line in pubspec.yaml

# 4. Easy Localization:
#    - Assets must be hot-reloaded to reflect translation changes
#    - Use 'r' in Flutter CLI to hot-reload
#    - Use 'R' to hot-restart if changes don't appear

# 5. Production Deployment:
#    - Run flutterfire configure with production Firebase project
#    - Update all assets (icons, splash screens)
#    - Enable minification for Android/iOS builds
#    - Test thoroughly on physical devices before uploading to stores

echo "All commands ready to use! Copy-paste them into PowerShell."
